# Generated by Django 4.2.23 on 2025-06-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('adfan', 'Administración de Familias y Niños (ADFAN)'), ('acuden', 'Administración para el Cuidado y Desarrollo Integral de la Niñez (ACUDEN)'), ('adsef', 'Administración de Desarrollo Socioeconómico de la Familia (ADSEF)'), ('asume', 'Administración para el Sustento de Menores (ASUME)'), ('secretariado', 'Secretariado del Departamento de la Familia')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
            },
        ),
        migrations.CreateModel(
            name='TipoPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Presentación',
                'verbose_name_plural': 'Tipos de Presentación',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ponente', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='presentaciones/')),
                ('imagen_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el portal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.administracion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.tipopresentacion')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['orden', 'fecha'],
            },
        ),
    ]
