# Generated by Django 4.2.23 on 2025-06-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='tipo',
        ),
    ]
