# Generated by Django 4.2.23 on 2025-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0002_remove_presentacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='video_bienvenida',
            field=models.FileField(blank=True, help_text='Video de bienvenida (MP4, WebM, OGV)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='codigo',
            field=models.CharField(choices=[('adfan', 'Administración de Familias y Niños (ADFAN)'), ('acuden', 'Administración para el Cuidado y Desarrollo Integral de la Niñez (ACUDEN)'), ('adsef', 'Administración de Desarrollo Socioeconómico de la Familia (ADSEF)'), ('asume', 'Administración para el Sustento de Menores (ASUME)'), ('secretariado', 'Secretariado del Departamento de la Familia'), ('ofi de lic.', 'Oficina de Licenciamiento')], max_length=20, unique=True),
        ),
    ]
