# Generated by Django 4.2.23 on 2025-06-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0003_presentacion_video_bienvenida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Video de Bienvenida', max_length=200)),
                ('video', models.FileField(help_text='Video de bienvenida del evento', upload_to='videos_bienvenida/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video de Bienvenida',
                'verbose_name_plural': 'Videos de Bienvenida',
            },
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='video_bienvenida',
        ),
    ]
