# Generated by Django 4.2.23 on 2025-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_adfan', models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='ADFAN')),
                ('evaluacion_acuden', models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='ACUDEN')),
                ('evaluacion_adsef', models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='ADSEF')),
                ('evaluacion_asume', models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='ASUME')),
                ('evaluacion_secretariado', models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Secretariado')),
                ('comentarios', models.TextField(blank=True, max_length=1000, verbose_name='Comentarios adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
